
### 1. Importing the data and helper function(s)

```{r}
library(readxl)
data <- read_excel("~/RStudio/CS_859_Team_Project/Dec1/Drug_Consumption_data_decade.xlsx")

f_cols = c("Gender", "Country", "Ethnicity", "Amphet", "Amyl", "Benzos", "Cannabis", "Crack", "Coke", "Ecstasy", "Legalh", "LSD", "Nicotine")

#drugs = list("Amphet", "Amyl", "Benzos", "Cannabis", "Coke", "Ecstasy", "Legalh", "LSD", "Nicotine")

data[f_cols] <- lapply(data[f_cols], factor)

data
```

```{r}
amphet = data[c("Age", "Nscore", "Oscore", "Cscore", "Impulsiveness", "SS", "Amphet")]

amyl = data[c("Nscore", "Oscore", "Cscore", "SS", "Amyl")]

benzos = data[c("Age", "Gender", "Nscore", "Escore", "Impulsiveness", "SS", "Benzos")]

cannabis = data[c("Age", "Education", "Oscore", "Ascore", "Cscore", "Impulsiveness", "Cannabis")]

crack = data[c("Escore", "Cscore", "Crack")]

coke = data[c("Age", "Oscore", "Ascore", "Impulsiveness", "SS", "Coke")]

ecstasy = data[c("Age", "Gender", "SS", "Ecstasy")]

legalh = data[c("Age", "Gender", "Oscore", "Ascore", "Cscore", "SS", "Legalh")]

lsd = data[c("Age", "Gender", "Nscore", "Escore", "Oscore", "Impulsiveness", "LSD")]

nicotine = data[c("Gender", "Nscore", "Escore", "Cscore", "Nicotine")]
```

```{r}
f1 <- function(rf_model)

{
p = rf_model$confusion[4]/(rf_model$confusion[3]+rf_model$confusion[4])
r = rf_model$confusion[4]/(rf_model$confusion[2]+rf_model$confusion[4])
#sp = rf_model$confusion[4]/(rf_model$confusion[2]+rf_model$confusion[4])
#se = rf_model$confusion[1]/(rf_model$confusion[2]+rf_model$confusion[4])

score = (2*p*r)/(r+p)

#sprintf('Sensitivity: %.4f', se)
#sprintf('Specificity: %.4f', sp)
sprintf('Precision: %.4f, Recall: %.4f, F1 Score: %.4f',  p, r,score)
}
```

### 2. Running a Random Forest

```{r}
library(randomForest)

set.seed(365)

rf_amp <- randomForest(Amphet~.,
                    data = amphet,
                    importance = TRUE,
                    mtry = 2,
                    ntree = 1000,
                    CUTOFF = .6,
                    verbose = TRUE)
print(rf_amp)
f1(rf_amp) #Positive Class F1 Score function
varImpPlot(rf_amp)
```

```{r}
set.seed(365)

rf_amyl <- randomForest(Amyl~.,
                    data = amyl,
                    importance = TRUE,
                    mtry = 2,
                    ntree = 1000,
                    CUTOFF = .6,
                    verbose = TRUE)
print(rf_amyl)
f1(rf_amyl) #Positive Class F1 Score function
varImpPlot(rf_amyl)
```

```{r}
set.seed(365)

rf_ben <- randomForest(Benzos~.,
                    data = benzos,
                    importance = TRUE,
                    mtry = 2,
                    ntree = 1000,
                    CUTOFF = .6,
                    verbose = TRUE)
print(rf_ben)
f1(rf_ben) #Positive Class F1 Score function
varImpPlot(rf_ben)
```

```{r}
set.seed(365)

rf_crack <- randomForest(Crack~.,
                    data = crack,
                    importance = TRUE,
                    mtry = 2,
                    ntree = 1000,
                    CUTOFF = .6,
                    verbose = TRUE)
print(rf_crack)
f1(rf_crack) #Positive Class F1 Score function
varImpPlot(rf_crack)
```

```{r}
set.seed(365)

rf_coke <- randomForest(Coke~.,
                    data = coke,
                    importance = TRUE,
                    mtry = 2,
                    ntree = 1000,
                    CUTOFF = .6,
                    verbose = TRUE)
print(rf_coke)
f1(rf_coke) #Positive Class F1 Score function
varImpPlot(rf_coke)
```

```{r}
set.seed(365)

rf_xt <- randomForest(Ecstasy~.,
                    data = ecstasy,
                    importance = TRUE,
                    mtry = 2,
                    ntree = 1000,
                    CUTOFF = .6,
                    verbose = TRUE)
print(rf_xt)
f1(rf_xt) #Positive Class F1 Score function
varImpPlot(rf_xt)
```

```{r}
set.seed(365)

rf_lh <- randomForest(Legalh~.,
                    data = legalh,
                    importance = TRUE,
                    mtry = 2,
                    ntree = 1000,
                    CUTOFF = .6,
                    verbose = TRUE)
print(rf_lh)
f1(rf_lh) #Positive Class F1 Score function
varImpPlot(rf_lh)
```
```{r}
set.seed(365)

rf_lsd <- randomForest(LSD~.,
                    data = lsd,
                    importance = TRUE,
                    mtry = 3,
                    ntree = 1000,
                    CUTOFF = .6,
                    verbose = TRUE)
print(rf_lsd)
f1(rf_lsd) #Positive Class F1 Score function
varImpPlot(rf_lsd)
```

```{r}
set.seed(365)

rf_nic <- randomForest(Nicotine~.,
                    data = nicotine,
                    importance = TRUE,
                    mtry = 2,
                    ntree = 1000,
                    CUTOFF = .6,
                    verbose = TRUE)
print(rf_nic)
f1(rf_nic) #Positive Class F1 Score function
varImpPlot(rf_nic)
```

